/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}'
  ],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        success: 'hsl(var(--success))',
        'success-foreground': 'hsl(var(--success-foreground))',
        tertiary: 'hsl(var(--tertiary))',
        'tertiary-foreground': 'hsl(var(--tertiary-foreground))',
        quaternary: 'hsl(var(--quaternary))',
        'quaternary-foreground': 'hsl(var(--quaternary-foreground))',
        outline: 'hsl(var(--outline))',
        'outline-variant': 'hsl(var(--outline-variant))',
        surface: 'hsl(var(--surface))',
        'surface-container': 'hsl(var(--surface-container))',
        'surface-container-low': 'hsl(var(--surface-container-low))',
        'surface-container-high': 'hsl(var(--surface-container-high))',
        'surface-bright': 'hsl(var(--surface-bright))',
        'on-surface': 'hsl(var(--on-surface))',
        'on-surface-variant': 'hsl(var(--on-surface-variant))',
        'on-primary': 'hsl(var(--on-primary))',
        'on-primary-container': 'hsl(var(--on-primary-container))',
        'primary-container': 'hsl(var(--primary-container))',
        'on-secondary': 'hsl(var(--on-secondary))',
        'secondary-container': 'hsl(var(--secondary-container))',
        'on-tertiary': 'hsl(var(--on-tertiary))',
        'tertiary-container': 'hsl(var(--tertiary-container))',
        error: 'hsl(var(--error))',
        'error-foreground': 'hsl(var(--error-foreground))',
        'error-container': 'hsl(var(--error-container))',
      },
      borderRadius: {
        DEFAULT: 'var(--radius-sm)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-lg)',
        '2xl': 'var(--radius-lg)',
        full: '9999px',
      },
      fontSize: {
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        h1: ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['18px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        body: ['15px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'ui-label': ['15px', { lineHeight: '1', letterSpacing: '0', fontWeight: '500' }],
        small: ['13px', { lineHeight: '1.5', letterSpacing: '0.01em', fontWeight: '400' }],
        caption: ['11px', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '500' }],
      },
      spacing: {
        unit: '4px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        gutter: '24px',
        '2xl': '32px',
        margin: '32px',
        '3xl': '48px',
      },
      fontFamily: {
        heading: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        body: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'ui-monospace', 'monospace'],
      },
      boxShadow: {
        pop: 'var(--shadow-pop)',
        'pop-hover': 'var(--shadow-pop-hover)',
        'pop-active': 'var(--shadow-pop-active)',
        sticker: 'var(--shadow-sticker)',
        'sticker-pink': 'var(--shadow-sticker-pink)',
        'sticker-primary': 'var(--shadow-sticker-primary)',
      },
      transitionTimingFunction: {
        bounce: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-4px)' },
        },
      },
      animation: {
        shimmer: 'shimmer 2s linear infinite',
        float: 'float 3s ease-in-out infinite',
      },
    },
  },
  safelist: [
    'border-success/50', 'bg-success/10', 'text-success',
    'border-error/50', 'bg-error/10', 'text-error',
    'focus:ring-success/30', 'focus:ring-error/30',
    'text-primary', 'text-secondary', 'text-tertiary', 'text-quaternary',
    'bg-primary', 'bg-secondary', 'bg-tertiary', 'bg-quaternary',
    'font-mono',
  ],
  plugins: [],
}
